---
title: "Parse USS Saufley Information"
author: "Rob Carnell"
date: "1/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(dplyr)
require(teseract)
require(magick)
require(XML) # for schema validation
require(lubridate)
require(xml2) # for working with XML
require(R6)
require(magrittr)
require(stringr)
require(plotKML)
require(sf)
require(sp)
require(stringr)
```

## Load the outline of the War Diaries and After Action Reports

```{r data, echo=FALSE}
X <- read.csv("../data/USS Saufley War Reports.csv", header = TRUE)

X$start_num <- NA
X$start_base_str <- NA
X$start_dir <- NA
for (i in 1:nrow(X))
{
  start_addr <- strsplit(X$First.Image[i], split = "[/]")[[1]]
  X$start_num[i] <- as.numeric(gsub("[.]jpg", "", start_addr[length(start_addr)]))
  start_base <- start_addr[3:(length(start_addr)-1)]
  X$start_base_str[i] <- paste0("https://", paste(start_base, sep = "", collapse = "/"))
  X$start_dir[i] <- paste0(i, "_", X$Date[i])
}
```

## Download Images for the War Diaries and After Action Reports

```{r downloads, eval=FALSE, include=FALSE}
if (!dir.exists("saufley_images"))
{
  dir.create("saufley_images")
}

for (i in 1:nrow(X))
{
  if (!dir.exists(file.path("saufley_images", X$start_dir[i])))
  {
    dir.create(file.path("saufley_images", X$start_dir[i]))
  }
  if (X$NARA.Name[i] == "USS SAUFLEY - Bombardment of Munda, 7/12/43 with Task Force 19")
  {
    download.file(url = paste0(X$start_base_str[i], "/", "1353.jpg"),
                  destfile = file.path("saufley_images", X$start_dir[i], "1353.jpg"),
                  mode = "wb")
    download.file(url = paste0(X$start_base_str[i], "/", "1357a.jpg"),
                  destfile = file.path("saufley_images", X$start_dir[i], "1357a.jpg"),
                  mode = "wb")
  } else
  {
    for (j in 1:X$Images[i])
    {
      base_file_name <- paste0(formatC(X$start_num[i] + j - 1, width = 4, flag = "0"), 
                             ".jpg")
      download_url <- paste0(X$start_base_str[i], "/", base_file_name)
      download.file(url = download_url,
                    destfile = file.path("saufley_images", X$start_dir[i], base_file_name),
                    mode = "wb")
    }
  }
}

```

## OCR the Images for the War Diaries

```{r ocr, eval=FALSE, include=FALSE}
#8.5 x 11 page with 80 lines in 9 inches at 32 pixels per line = 80*32/9*11 = 3129

processImage <- function(file_name, fuzz, simple = FALSE)
{
  # file_name <- file.path("saufley_images", X$start_dir[i], base_file_name)
  txt <- magick::image_read(file_name) %>%
    # resize to capital letters at about 32 pixels
    magick::image_resize(geometry = magick::geometry_area(height = 3129)) %>%
    # trim the black border around the scanned page
    magick::image_trim(fuzz = fuzz) 
  
  if (!simple)
    txt <- txt %>%
    # switch to a dark background
    magick::image_negate() %>%
    # minimize noise
    magick::image_enhance() %>%
    # inflate the contrast between light and dark
    magick::image_contrast(sharpen = 1) %>%
    # crop a half inch off the top and left
    magick::image_chop(geometry = magick::geometry_area(width = 120, height =  120))
  
  txt <- txt %>%
    magick::image_ocr()
  
  return(txt)
}

for (i in 1:nrow(X))
{
  cat("Parsing", i, "\n")
  if (X$Type[i] == "War Diary")
  {
    withr::with_connection(list(con = file(file.path("saufley_images", X$start_dir[i],
                                                paste0(X$start_dir[i], ".txt")), "w")), {
      for (j in 1:X$Images[i])
      {
        cat("\t", j, "\n")
        base_file_name <- paste0(formatC(X$start_num[i] + j - 1, width = 4, flag = "0"), 
                             ".jpg")
        #txt <- tesseract::ocr(file.path("saufley_images", X$start_dir[i], base_file_name))
        try_again <- TRUE
        tryCatch({
          txt <- processImage(file.path("saufley_images", X$start_dir[i], base_file_name), 90)
          try_again <- FALSE
        }, error = function(e) {cat("Error Trying again\n")})
        if (try_again) 
          txt <- processImage(file.path("saufley_images", X$start_dir[i], base_file_name), 0, TRUE)
        writeLines(txt, con)
      }
    })
  }
}


```

## Download the Muster roll Images

See [here](https://catalog.archives.gov/id/192340822)

```{r download-muster-roll, eval=FALSE}
if (!dir.exists("../img/muster"))
{
  dir.create("../img/muster")
}

for (i in 0:1445)
{
  print(i)
  base_file_name <- paste0(stringr::str_pad(i, width = 5, pad = "0"),
                           ".jpg")
  
  download_url <- paste0("https://catalog.archives.gov/catalogmedia/lz/",
                         "partnerships/32862/0001/DD00677/32862_252285/",
                         "32862_252285-", base_file_name)

  dest_file_name <- paste0("../img/muster/muster-", base_file_name)

  download.file(url = download_url, destfile = dest_file_name, mode = "wb")
}

```

## Create an Outline for Transcription

```{r transcipt, eval=FALSE}
cat("/* START */\n", file = "USS_Saufley_WarReports.xml", append = FALSE)
for (i in 1:nrow(X))
{
  cat("<source>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <name>", X$NARA.Name[i], "</name>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <type>", X$Type[i], "</type>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <date>", X$Date[i], "</date>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <url>", X$First.Image[i], "</url>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <directory>", file.path("saufley_images", X$start_dir[i]), "</directory>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("  <images>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
  if (X$NARA.Name[i] == "USS SAUFLEY - Bombardment of Munda, 7/12/43 with Task Force 19")
  {
      cat("    <image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <file>", "1353.jpg", "</file>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        <item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <date></date>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <time></time>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <latitude></latitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <longitude></longitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <decription></description>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        </item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      </items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("    </image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("    <image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <file>", "1357a.jpg", "</file>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        <item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <date></date>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <time></time>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <latitude></latitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <longitude></longitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <decription></description>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        </item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      </items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("    </image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
  } else
  {
    for (j in 1:X$Images[i])
    {
      cat("    <image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <file>", paste0(formatC(X$start_num[i] + j - 1, width = 4, flag = "0"), 
                           ".jpg"), "</file>\n", sep = "", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("      <items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        <item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <date></date>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <time></time>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <latitude></latitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <longitude></longitude>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("          <decription></description>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("        </item>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)

      cat("      </items>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
      cat("    </image>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
    }
  }
  cat("  </images>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
  cat("</source>\n", file = "USS_Saufley_WarReports.xml", append = TRUE)
}
```

## Validate the XML

```{r validate-xml, echo=FALSE}
temp <- XML::xmlSchemaValidate(XML::xmlSchemaParse("../doc/USS_Saufley_WarReports.xsd"),
                       XML::xmlParse("../doc/USS_Saufley_WarReports.xml"))
sapply(temp[[2]], function(x) {print(x$msg); print(x$line)})
```

### XML Classes

```{r xml-classes, echo=FALSE}
Source <- R6::R6Class("Source",
  public = list(
    initialize = function(source_node){
      assertthat::assert_that(xml2::xml_name(source_node) == "source")
      private$name <- xml2::xml_text(xml2::xml_find_first(source_node, ".//name"))
      private$type <- xml2::xml_text(xml2::xml_find_first(source_node, ".//type"))
      private$date <- xml2::xml_text(xml2::xml_find_first(source_node, ".//date"))
      private$url <- xml2::xml_text(xml2::xml_find_first(source_node, ".//url"))
      private$directory <- xml2::xml_text(xml2::xml_find_first(source_node, ".//directory"))
      temp_images <- xml2::xml_find_all(source_node, ".//images/image")
      private$images <- lapply(temp_images, function(z) return(Image$new(z)))
    },
    get_metadata = function(){
      return(list(name = private$name, 
                  type = private$type, 
                  date = private$date, 
                  url = private$url, 
                  directory = private$directory))
    },
    get_images = function(){
      return(private$images)
    }
  ),
  private = list(
    name = character(),
    type = character(),
    date = character(),
    url = character(),
    directory = character(),
    images = list()
  )
)
Image <- R6::R6Class("Image",
  public = list(
    initialize = function(image_node){
      assertthat::assert_that(xml2::xml_name(image_node) == "image")
      private$filename <- xml2::xml_text(xml2::xml_find_first(image_node, ".//file"))
      temp_items <- xml2::xml_find_all(image_node, ".//items/item")
      private$items <- lapply(temp_items, function(z) return(Item$new(z)))
    },
    get_filename = function(){
      return(private$filename)
    },
    get_items = function(){
      return(private$items)
    }
  ),
  private = list(
    filename = character(),
    items = list()
  )
)
Item <- R6::R6Class("Item",
  public = list(
    initialize = function(item_node){
      assertthat::assert_that(xml2::xml_name(item_node) == "item")
      private$date <- xml2::xml_text(xml2::xml_find_first(item_node, ".//date"))
      private$description <- xml2::xml_text(xml2::xml_find_first(item_node, ".//description"))
      temp_posits <- xml2::xml_find_all(item_node, ".//posit")
      private$posits <- lapply(temp_posits, function(z) Posit$new(z))
    },
    get_date = function(){
      return(private$date)
    },
    get_description = function(){
      return(private$description)
    },
    get_posits = function(){
      return(do.call("rbind", lapply(private$posits, function(z) z$get())))
    }
  ),
  private = list(
    date = character(),
    description = character(),
    posits = list()
  )
)
Posit <- R6::R6Class("Posit",
  public = list(
    initialize = function(posit_node){
      assertthat::assert_that(xml2::xml_name(posit_node) == "posit")
      private$time <- xml2::xml_attr(posit_node, "time")
      private$lat <- xml2::xml_attr(posit_node, "lat")
      private$lon <- xml2::xml_attr(posit_node, "lon")
    },
    get = function(){
      return(c(time = private$time,
                  lat = self$translate_lat(private$lat),
                  lon = self$translate_lat(private$lon)))
    },
    translate_lat = function(slat){
      lsign <- ifelse(grepl("N", slat) | grepl("E", slat), 1, -1)
      lnum <- slat %>%
        stringr::str_extract("[0-9]*[-][0-5][0-9][-][0-5][0-9]") %>%
        stringr::str_split("-") %>%
        magrittr::extract2(1) %>%
        as.numeric()
      ret <- (lnum[1] + lnum[2]/60 + lnum[3]/3600) * lsign
      if (is.na(ret))
      {
        warning(paste0("Potentially malformed Lat/Long in ", slat))
      }
      return(ret)
    }
  ),
  private = list(
    time = character(),
    lat = character(),
    lon = character()
  )
)
```

### Read and Extract

```{r read-and-extract, echo=FALSE}
X <- xml2::read_xml("../doc/USS_Saufley_WarReports.xml")
source_list <- lapply(xml2::xml_find_all(X, ".//source"), function(z) Source$new(z))

source_metadata <- do.call("rbind", lapply(source_list, function(z) z$get_metadata()))


latlon <- lapply(source_list, function(z) {
  do.call("rbind", lapply(z$get_images(), function(w) {
    do.call("rbind", lapply(w$get_items(), function(d) {
      tempdf <- d$get_posits()
      tempdf <- data.frame(time = tempdf[,1],
                           lat = as.numeric(tempdf[,2]),
                           lon = as.numeric(tempdf[,3]))
      if (nrow(tempdf) > 0){
        tempdf$date <- as.Date(d$get_date())
        tempdf$Description <- paste0("\n<h3>", tempdf$date, ": ", tempdf$time, 
                                    "</h3>\n", d$get_description())
        tempdf$Name <- paste(stringr::str_pad(lubridate::day(tempdf$date), 
                                              width = 2, pad = "0"),
                             tempdf$time)
      }
      return(tempdf)
    }))
  }))
})
```

### rgdal method

```{r rgdal-method, eval=FALSE}
require(sp)

plot_data_full <- do.call("rbind", latlon[c(1, 39)])

plot_data <- plot_data_full %>%
  dplyr::filter(date >= as.Date("1945-01-01"), date <= as.Date("1945-12-31"))

kml_file_name <- "test.kml"
points_kml_file_name <- "test_points.kml"
lines_kml_file_name <- "test_lines.kml"

plot_coords <- plot_data %>% dplyr::select(lon, lat)
plot_desc <- plot_data %>% dplyr::select(Name, Description)

spatial_points <- sp::SpatialPointsDataFrame(plot_coords,
  proj4string = sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"),
  data = plot_desc)

spatial_line <- sp::Line(plot_coords)
spatial_lines <- sp::Lines(list(spatial_line), ID = "A")
spatial_lines_obj <- sp::SpatialLines(list(spatial_lines),
  proj4string = sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))
spatial_lines_group <- sp::SpatialLinesDataFrame(
  spatial_lines_obj,
  data = data.frame(Name = "1945"),
  match.ID = FALSE)

rgdal::writeOGR(spatial_points, dsn=points_kml_file_name, layer = "1945-Points", 
                driver="KML", overwrite_layer = TRUE)

rgdal::writeOGR(spatial_lines_group, dsn=lines_kml_file_name, layer = "1945-Lines", 
                driver="KML", overwrite_layer = TRUE)
```

### Maptools Method

```{r maptools-method, eval=FALSE}
require(maptools)
require(sp)

maptools::kmlPoints(spatial_points, kmlfile = "test2_points.kml", 
  name = plot_data$Name, 
  description = plot_data$Description,
  icon = "http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png", 
  kmlname = "1945-Locations", 
  kmldescription = "")

maptools::kmlLines(spatial_lines_group, kmlfile = "test2_lines.kml", 
  name = "Route",
  description = "", 
  col = "white", visibility = 1, lwd = 1,
  kmlname = "1945-Route", 
  kmldescription = "")

temp <- readLines("test2_points.kml")
ind <- grep("</Style>", temp)
temp1 <- temp[1:(ind-1)]
temp2 <- temp[ind:length(temp)]
temp_insert <- c(
  '<BalloonStyle>',
  '<bgColor>ffffffbb</bgColor>',
  '<text>',
  '<![CDATA[<font face="Courier">$[description]</font>]]>',
  '</text>',
  '</BalloonStyle>')
writeLines(c(temp1, temp_insert, temp2), "test2_points.kml")
```

### plotKML method

```{r plot-linestring, echo=FALSE}
## INTERNAL VERSION OF plotKML:::.kml_layer_sfc_LINESTRING

my_kml_layer_sfc_LINESTRING <- function(
  obj,
  subfolder.name = paste(class(obj)),
  extrude = FALSE,
  z.scale = 1,
  metadata = NULL,
  html.table = NULL,
  TimeSpan.begin = "",
  TimeSpan.end = "",
  ...
) {
  kml.out <- get("kml.out", envir = plotKML.fileIO)
  
  if (is.na(sf::st_crs(obj)) || is.null(sf::st_crs(obj))) {
    stop("CRS of obj is missing")
  }
  if (!sf::st_is_longlat(obj) || st_crs(obj) != st_crs(4326)) {
    obj <- sf::st_transform(obj, crs = 4326)
    message("Reprojecting to ", get("ref_CRS", envir = plotKML.opts))
  }
  
  aes <- kml_aes(obj, ...)
  
  lines_names <- aes[["labels"]]
  colours <- aes[["colour"]]
  widths <- aes[["width"]]
  altitude <- aes[["altitude"]]
  altitudeMode <- aes[["altitudeMode"]]
  balloon <- aes[["balloon"]]
  
  if (
    balloon & 
    (inherits(obj, "sf") ||  (isS4(obj) && "data" %in% slotNames(obj)))
  ) {
    html.table <- .df2htmltable(obj)
  }
  
  message("Writing to KML...")
  pl1 = newXMLNode("Folder", parent = kml.out[["Document"]])
  pl2 <- newXMLNode("name", subfolder.name, parent = pl1)
  
  if (!is.null(metadata)) {
    md.txt <- kml_metadata(metadata, asText = TRUE)
    txtm <- sprintf('<description><![CDATA[%s]]></description>', md.txt)
    parseXMLAndAdd(txtm, parent=pl1)
  }
  
  lv <- length(sf::st_geometry(obj)) 
  coords <- NULL
  for (i.line in seq_len(lv)) {
    xyz <- matrix(sf::st_coordinates(obj[i.line])[, 1:2], ncol = 2)
    xyz <- cbind(xyz, rep(altitude[i.line], nrow(xyz)))
    coords[[i.line]] <- paste(xyz[, 1], ',', xyz[, 2], ',', xyz[, 3], collapse='\n ', sep = "")
  }
  
  txts <- sprintf(
    '<Style id="line%s"><LineStyle><color>%s</color><width>%.0f</width></LineStyle><BalloonStyle><text>$[description]</text></BalloonStyle></Style>', 
    seq_len(lv), 
    colours, 
    widths
  )
  parseXMLAndAdd(txts, parent=pl1)
  
  if (length(html.table) > 0) {
    if (nzchar(TimeSpan.begin[1]) & nzchar(TimeSpan.end[1])) {
      if (identical(TimeSpan.begin, TimeSpan.end)) {
        when = TimeSpan.begin
        if (length(when) == 1L){
          when = rep(when, lv) 
        }
        txt <- sprintf(
          '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><TimeStamp><when>%s</when></TimeStamp><description><![CDATA[%s]]></description><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
          lines_names, 
          seq_len(lv), 
          when, 
          html.table, 
          rep(as.numeric(extrude), lv), 
          rep(altitudeMode, lv), 
          paste(unlist(coords))
        )
      } else {
        if (length(TimeSpan.begin) == 1L) {
          TimeSpan.begin = rep(TimeSpan.begin, lv) 
        }
        if (length(TimeSpan.end) == 1L) {
          TimeSpan.end = rep(TimeSpan.end, lv) 
        }
        txt <- sprintf(
          '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><TimeSpan><begin>%s</begin><end>%s</end></TimeSpan><description><![CDATA[%s]]></description><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
          lines_names, 
          seq_len(lv), 
          TimeSpan.begin, 
          TimeSpan.end, 
          html.table, 
          rep(as.numeric(extrude), lv), 
          rep(altitudeMode, lv), 
          paste(unlist(coords))
        )    
      }
    } else {      
      txt <- sprintf(
        '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><description><![CDATA[%s]]></description><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
        lines_names, 
        seq_len(lv), 
        html.table, 
        rep(as.numeric(extrude), lv), 
        rep(altitudeMode, lv), 
        paste(unlist(coords))
      )
    }
  } else {
    if (nzchar(TimeSpan.begin[1]) & nzchar(TimeSpan.end[1])) {
      if (identical(TimeSpan.begin, TimeSpan.end)) {
        when = TimeSpan.begin
        if (length(when) == 1L) {
          when = rep(when, lv) 
        }
        txt <- sprintf(
          '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><TimeStamp><when>%s</when></TimeStamp><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
          lines_names, 
          seq_len(lv), 
          when, 
          rep(as.numeric(extrude), lv), 
          rep(altitudeMode, lv), 
          paste(unlist(coords))
        )
      } else {
        if (length(TimeSpan.begin) == 1L){
          TimeSpan.begin = rep(TimeSpan.begin, lv)
        }
        if (length(TimeSpan.end) == 1L){
          TimeSpan.end = rep(TimeSpan.end, lv)
        }   
        txt <- sprintf(
          '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><TimeSpan><begin>%s</begin><end>%s</end></TimeSpan><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
          lines_names, 
          seq_len(lv), 
          TimeSpan.begin, 
          TimeSpan.end, 
          rep(as.numeric(extrude), lv), 
          rep(altitudeMode, lv), 
          paste(unlist(coords))
        )
      }     
    } else {
      txt <- sprintf(
        '<Placemark><name>%s</name><styleUrl>#line%s</styleUrl><LineString><extrude>%.0f</extrude><altitudeMode>%s</altitudeMode><coordinates>%s</coordinates></LineString></Placemark>', 
        lines_names, 
        seq_len(lv), 
        rep(as.numeric(extrude), lv), 
        rep(altitudeMode, lv), 
        paste(unlist(coords))
      ) 
    }
  }
  
  parseXMLAndAdd(txt, parent=pl1)
  
  assign('kml.out', kml.out, envir=plotKML.fileIO)
}
```

## Output KML Layers

```{r plot-kml, echo=FALSE, message=FALSE}
include_series <- c(1, 37, 38, 39, 41)

# need to put the include_series in date order
first_dates <- do.call("c", lapply(include_series, function(z) latlon[[z]]$date[1]))

# loop over years
for (k in 1942:1945)
{
  ind <- which(lubridate::year(first_dates) == k)
  
  if (length(ind) == 0)
    next
  
  year_file <- paste0("test", k, ".kml")
  series_in_year <- include_series[ind]
  dates_in_year <- first_dates[ind]

  ord <- order(dates_in_year)
  
  plotKML::kml_open(year_file, folder.name = k)
  
  for (i in include_series[ord])
  {
    plot_data <- latlon[[i]]
    plot_coords <- plot_data %>% dplyr::select(lon, lat) # must go lon then lat (x then y)
    
    sf_points <- sf::st_sfc(sf::st_multipoint(as.matrix(plot_coords), dim = "XY"))
    sf_points <- sf::st_set_crs(sf_points, 4326)
  
    point_time <- strptime(paste(plot_data$date, plot_data$time), 
                           format = "%Y-%m-%d %H%M", tz = "GMT")
  
    ym <- paste0(lubridate::year(plot_data$date[1]), "-",
                 stringr::str_pad(lubridate::month(plot_data$date[1]), 
                                  width = 2, pad = "0"))
  
    plotKML::kml_layer(sf::st_cast(sf_points, "POINT"),
      subfolder.name = paste(ym, "Locations"), 
      points_names = plot_data$Name, 
      html.table = plot_data$Description,
      TimeSpan.begin = format(point_time, "%Y-%m-%dT%H:%M:%SZ"),
      TimeSpan.end = format(point_time + 60, "%Y-%m-%dT%H:%M:%SZ"),
      shape = "http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png", 
      colour = "orange")
  
    sf_lines <- sf::st_linestring(as.matrix(plot_coords[1:2,]), dim = "XY")
    for (j in 2:(nrow(plot_data) - 1))
    {
      sf_lines <- c(sf_lines, sf::st_linestring(as.matrix(plot_coords[j:(j+1),]), dim = "XY"))
    }
    sf_lines <- sf::st_sfc(sf_lines)
  
    sf_lines <- sf::st_set_crs(sf_lines, 4326)
  
    templen <- nrow(plot_data) - 1
  
    my_kml_layer_sfc_LINESTRING(sf::st_cast(sf_lines, "LINESTRING"),
      subfolder.name = paste(ym, "Routes"),
      TimeSpan.begin = format(point_time[1:templen], "%Y-%m-%dT%H:%M:%SZ"),
      TimeSpan.end = format(point_time[1:templen] + 60, "%Y-%m-%dT%H:%M:%SZ"),
      colour = "orange",
      labels = plot_data$Name[1:templen])
  }
  
  plotKML::kml_close(year_file)
}

```



